AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: "Bref demo for Laravel"

Globals:
  Function:
    Environment:
      Variables:
        # Laravel environment variables
        APP_STORAGE: "/tmp/laravel"

Resources:
  Website:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: "bref-demo-laravel-website"
      CodeUri: .
      Handler: public/index.php
      Timeout: 30 # in seconds (API Gateway has a timeout of 30 seconds)
      Runtime: provided
      Role: arn:aws:iam::102183358164:role/LabRole
      Layers:
        - "arn:aws:lambda:us-east-2:209497400698:layer:php-73-fpm:1"
      Events:
        # The function will match all HTTP URLs
        HttpRoot:
          Type: Api
          Properties:
            Path: /
            Method: ANY
        HttpSubPaths:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
# Outputs show up in the CloudFormation dashboard
Outputs:
  DemoHttpApi:
    Description: "URL of our function in the *Prod* environment"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"