name: CI

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: php-actions/composer@v6
      with:
        working_dir: ./api
    - uses: php-actions/phpunit@v3
      with:
        working_dir: ./api